import { spawnSync } from "child_process";
import { mkdirSync } from "fs";
import { join } from "path";
import { downloadConvexBinary } from "./downloadConvexBinary";
import { ConvexHttpClient } from "convex/browser";
import { findUnusedPort, waitForHttpOk, onProcessExit } from "./lib";
import { execa, type ResultPromise } from "execa";
import kill from "tree-kill";

const INSTANCE_NAME = "carnitas";
const INSTANCE_SECRET =
  "4361726e697461732c206c69746572616c6c79206d65616e696e6720226c6974";
// This admin key is generated by the Convex CLI for the carnitas instance with the above secret
const ADMIN_KEY =
  "0135d8598650f8f5cb0f30c34ec2e2bb62793bc28717c8eb6fb577996d50be5f4281b59181095065c5d0f86a2c31ddbe9b597ec62b47ded69782cd";

export class ConvexBackend {
  public port?: number;
  public siteProxyPort?: number;
  public process?: ResultPromise;
  public readonly adminKey = ADMIN_KEY;
  public backendUrl?: string;
  private _client?: ConvexHttpClient;

  private readonly projectDir: string;
  private readonly stdio: "inherit" | "ignore" | ["ignore", "pipe", "pipe"];

  get client(): ConvexHttpClient {
    if (!this._client) throw new Error("Backend not initialized");
    return this._client;
  }

  constructor(
    options: {
      projectDir?: string;
      stdio?: "inherit" | "ignore" | ["ignore", "pipe", "pipe"];
    } = {},
  ) {
    this.projectDir = options.projectDir ?? process.cwd();
    this.stdio = options.stdio ?? "inherit";
  }

  async init(): Promise<void> {
    const backendDir = join(this.projectDir, ".convex-e2e-test");

    console.log("🚀 Starting Convex backend...");
    await this.startBackend(backendDir);
    console.log(`✅ Backend running on port ${this.port}`);

    console.log("📦 Deploying Convex code...");
    await this.deploy();
    console.log("✅ Deploy successful!");

    this.backendUrl = `http://localhost:${this.port}`;
    this._client = new ConvexHttpClient(this.backendUrl);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (this._client as any).setAdminAuth(this.adminKey);

    console.log(`✅ Convex backend ready at ${this.backendUrl}\n`);

    onProcessExit(() => this.stop());
  }

  private async startBackend(backendDir: string): Promise<void> {
    const storageDir = join(backendDir, "convex_local_storage");
    mkdirSync(storageDir, { recursive: true });

    const sqlitePath = join(backendDir, "convex_local_backend.sqlite3");
    const convexBinary = await downloadConvexBinary();

    this.port = findUnusedPort();
    this.siteProxyPort = findUnusedPort();

    this.process = execa(
      convexBinary,
      [
        "--port",
        String(this.port),
        "--site-proxy-port",
        String(this.siteProxyPort),
        "--instance-name",
        INSTANCE_NAME,
        "--instance-secret",
        INSTANCE_SECRET,
        "--local-storage",
        storageDir,
        sqlitePath,
      ],
      {
        cwd: backendDir,
        stdio: this.stdio,
      },
    );

    // Handle process exit (expected when we call stop())
    this.process.catch(() => {
      // Process was terminated, this is expected
    });

    // Wait for the backend to be healthy
    await this.healthCheck();

    // Verify the process has a PID (started successfully)
    if (!this.process.pid) {
      throw new Error("Convex process failed to start - no PID assigned");
    }
  }

  private async healthCheck(): Promise<void> {
    if (!this.port) throw new Error("Port not set for health check");
    const url = `http://localhost:${this.port}/version`;
    await waitForHttpOk(url, 10_000);
  }

  private async deploy(): Promise<void> {
    if (!this.port) throw new Error("Backend not started");

    const backendUrl = `http://localhost:${this.port}`;
    console.log(`   Running: npx convex deploy --url ${backendUrl}`);

    const deployResult = spawnSync(
      "npx",
      ["convex", "deploy", "--admin-key", this.adminKey, "--url", backendUrl],
      {
        cwd: this.projectDir,
        encoding: "utf-8",
        stdio: ["ignore", "pipe", "pipe"],
        timeout: 60000,
      },
    );

    if (deployResult.error)
      throw new Error(
        `Failed to spawn convex deploy: ${deployResult.error.message}`,
      );

    if (deployResult.status !== 0) {
      const output = deployResult.stdout + deployResult.stderr;
      if (output.includes("DeploymentNotConfiguredForNodeActions")) {
        throw new Error(
          `E2E tests require Node.js 18, 20, or 22 for "use node" actions.\n` +
          `Current Node version may not be supported by Convex local backend.\n` +
          `Install a supported version with: nvm install 22 && nvm use 22\n\n` +
          `Original error:\n${output}`,
        );
      }
      throw new Error(
        `Failed to deploy (exit code ${deployResult.status}):\n${output}`,
      );
    }

    await this.setEnv("IS_TEST", "true");
  }

  async setEnv(name: string, value: string): Promise<void> {
    if (!this.port) throw new Error("Backend not started");

    const backendUrl = `http://localhost:${this.port}`;
    const displayValue = value.length > 50 ? `${value.slice(0, 50)}...` : value;
    console.log(`   Setting env var ${name} = "${displayValue}"`);

    // Use the Convex Deployment API to set environment variables
    const response = await fetch(
      `${backendUrl}/api/v1/update_environment_variables`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Convex ${this.adminKey}`,
        },
        body: JSON.stringify({
          changes: [
            {
              name,
              value,
            },
          ],
        }),
      },
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Failed to set ${name} env via API (${response.status}): ${errorText}`,
      );
    }

    console.log(`   ✓ Successfully set ${name}`);
  }

  async stop(): Promise<void> {
    if (!this.process || this.process.pid === undefined) return;

    console.log(`🛑 Stopping Convex backend...`);

    const pid = this.process.pid;
    try {
      // Try graceful SIGTERM first, tree-kill will kill all child processes
      await new Promise<void>((resolve, reject) => {
        kill(pid, "SIGTERM", (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
    } catch (error) {
      console.warn(`Failed to terminate Convex backend gracefully:`, error);
    }
  }
}
